<a href="https://colab.research.google.com/github/groovyxw/ML_Iris_Classification/blob/main/python_data_science_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Python function

In [1]:
#multiply two numbers using a python function
def multiply(x,y):
    z = x*y
    return z
#call the function to multiply the numbers 2 and 3
multiply(2,3)

6

# 2. Python data types and sequences

In [2]:
type(' My name is Rohan')


str

In [3]:
type(1)

int

In [4]:
type(1.0)

float

In [5]:
type(None) #None signifies 'no value' or 'empty value'

NoneType

In [6]:
type(multiply) #multiply is a function we created previously

function

## i. Tuples : They are immutable data structures which cannot be altered unlike lists

In [7]:
a = (1,2,3,4)
type(a)

tuple

## ii. Lists : They are mutable objects

In [8]:
b = [1,2,3,4]
type(b)

list

In [9]:
b.append(2.2) #append to list using this function
print(b)

[1, 2, 3, 4, 2.2]


In [10]:
for number in b: #looping through list
    print(number)

1
2
3
4
2.2


In [11]:
[1,2,3] + [1,'abc','de'] #concatenate lists

[1, 2, 3, 1, 'abc', 'de']

In [12]:
[1,2]*3 #repeat lists

[1, 2, 1, 2, 1, 2]

In [13]:
3 in b #in operator to check if required object is in list

True

In [14]:
a,b = ('abc','def')
print(a)
print(b)

abc
def


## iii. Strings : A string stores character objects

In [15]:
x = 'My name is Rohan'

In [16]:
x[0] #Access first letter

'M'

In [17]:
x[0:2] #Accesses two letters

'My'

In [18]:
x[:-1] #Accesses everything except last letter

'My name is Roha'

In [19]:
x[10:] #returns all the characters from 10th position till end

' Rohan'

In [20]:
first = 'Rohan'
last = 'Joseph'

Name = first + ' ' + last #string concatenation
print(Name)

Rohan Joseph


In [21]:
Name.split(' ') #split the words in a string using split function

['Rohan', 'Joseph']

In [22]:
Name.split(' ')[0] #Show the first word

'Rohan'

In [23]:
Name.split(' ')[1] #Show the second word

'Joseph'

In [24]:
#for concatenation convert objects to strings
'Rohan' + str(2)

'Rohan2'

## iv. Dictionary : A dictionary is a collection which is not ordered, but is indexed — and they have keys and values.

In [25]:
c = {"Name" : "Rohan", "Height" : 176}
type(c)

dict

In [26]:
print(c)

{'Name': 'Rohan', 'Height': 176}


In [27]:
c['Height']

176

In [28]:
#print all the keys
for i in c:
    print(i)

Name
Height


In [29]:
for i in c.values():
    print(i)

Rohan
176


In [30]:
for name, height in c.items():
    print(name)
    print(height)

Name
Rohan
Height
176


3. Python Date and Time

In [31]:
import datetime as dt
import time as tm

In [32]:
tm.time() #print current time in seconds from January 1, 1970

1659762961.9292831

In [33]:
#convert timestamp to datetime
dtnow = dt.datetime.fromtimestamp(tm.time()) 
dtnow.year

2022

In [34]:
today = dt.date.today()
today

datetime.date(2022, 8, 6)

In [35]:
delta = dt.timedelta(days=100)
today - delta

datetime.date(2022, 4, 28)

# 4. Map function

In [36]:
a = [1,2,3,10]
b = [5,6,2,9]

c = map(min,a,b) #Find the minimum between two pairs of lists
for item in c:
    print(item) #print the minimum of the pairs

1
2
2
9


# 5. Lambda function

In [37]:
function = lambda a,b,c : a+b+c #function to add three numbers
function(2,2,3) #call the function


7

# 6. Filter function

In [38]:
x = [1,2,3,4,5,6,7,8,9] #create a list
x2 = filter(lambda a : a>5, x) #filter using filter function
print(list(x2))

[6, 7, 8, 9]


# 7. Reduce function

In [39]:
from functools import reduce #import reduce function
y = [1,2,3,4,5] #create list
reduce(lambda a,b : a*b,y) #use reduce

120

# 8. Zip function

In [40]:
a = [1,2,3,4] #create two lists
b = [5,6,7,8]
c = zip(a,b) #Use the zip function
print(list(c))

[(1, 5), (2, 6), (3, 7), (4, 8)]


# 9. For loop

In [41]:
#return even numbers from 1 to 100

even=[]
for i in range(100):
    if i%2 ==0:
        even.append(i)
    else:
        None
print(even) #print the list

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


# 10. List comprehension

In [42]:
even = [i for i in range(100) if i%2==0]
print(even)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


# Part2

## The Numpy library

In [43]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [44]:
a = np.array([[1,2,3],[4,5,6]]) 
a

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
a.shape

(2, 3)

In [46]:
b = np.arange(1,30,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [47]:
b.reshape(5,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

In [48]:
c = np.linspace(1,5,20)
c

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [49]:
c.resize(5,4)
c

array([[1.        , 1.21052632, 1.42105263, 1.63157895],
       [1.84210526, 2.05263158, 2.26315789, 2.47368421],
       [2.68421053, 2.89473684, 3.10526316, 3.31578947],
       [3.52631579, 3.73684211, 3.94736842, 4.15789474],
       [4.36842105, 4.57894737, 4.78947368, 5.        ]])

In [50]:
d = np.ones((2,2))
d

array([[1., 1.],
       [1., 1.]])

In [51]:
e = np.zeros((3,3))
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [53]:
np.diag(f)

array([1., 1.])

In [54]:
g = np.array([1,2,3]*5)
g

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [55]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [56]:
g = np.random.rand(2,3)
print(g)
h = np.random.rand(2,3)
print(h)

[[0.99884459 0.68983779 0.94605324]
 [0.87809134 0.58594986 0.60147525]]
[[0.75153078 0.36453515 0.59091972]
 [0.87952893 0.65367351 0.4155584 ]]


In [57]:
i = np.vstack([h,g])
i

array([[0.75153078, 0.36453515, 0.59091972],
       [0.87952893, 0.65367351, 0.4155584 ],
       [0.99884459, 0.68983779, 0.94605324],
       [0.87809134, 0.58594986, 0.60147525]])

In [58]:
j = np.hstack([h,g])
j

array([[0.75153078, 0.36453515, 0.59091972, 0.99884459, 0.68983779,
        0.94605324],
       [0.87952893, 0.65367351, 0.4155584 , 0.87809134, 0.58594986,
        0.60147525]])

In [59]:
k = np.random.rand(2,2)
l = np.random.rand(2,2)
print(k)
print(l)

[[0.08885394 0.56531477]
 [0.43771375 0.20172821]]
[[0.3436734  0.79918019]
 [0.44008229 0.34161216]]


In [60]:
m = k + l
m

array([[0.43252735, 1.36449496],
       [0.87779604, 0.54334037]])

In [61]:
n = k-l
n

array([[-0.25481946, -0.23386543],
       [-0.00236855, -0.13988395]])

In [62]:
p = k**2
p

array([[0.00789502, 0.31958079],
       [0.19159333, 0.04069427]])

In [63]:
q = k.dot(l)
q

array([[0.27932176, 0.26412871],
       [0.23920759, 0.41872497]])

In [64]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [65]:
a.T

array([[1, 3],
       [2, 4]])

In [66]:
a.dtype

dtype('int64')

In [67]:
b = a.astype('f')
b.dtype

dtype('float32')

In [68]:
c = np.array([1,2,3,4,5])
c.sum()

15

In [69]:
c.max()

5

In [70]:
c.mean()

3.0

In [71]:
c.argmax()

4

In [72]:
c.argmin()

0

In [73]:
d = np.arange(10)**2
d

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [74]:
d[2]


4

In [75]:
d[1:5]


array([ 1,  4,  9, 16])

In [76]:
d[-1:]


array([81])

In [77]:
d[1:10:2] #d[start:stop:stepsize]

array([ 1,  9, 25, 49, 81])

In [78]:
e = np.arange(36)
e.resize(6,6)
e

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [79]:
e[1,2]

8

In [80]:
e[1, 2:6]

array([ 8,  9, 10, 11])

In [81]:
e[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [82]:
e[e>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [83]:
e[e>20] = 20
e

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [84]:
f = e.copy()
f

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [85]:
g = np.random.randint(1,10,(4,4))
g

array([[4, 8, 4, 7],
       [1, 1, 6, 3],
       [7, 1, 4, 2],
       [4, 2, 3, 7]])

# Part 3

## 1. Pandas Series

In [86]:
import pandas as pd
import numpy as np

In [87]:
name = ['Rohan','Joseph','Rohit']
name

['Rohan', 'Joseph', 'Rohit']

In [88]:
name = pd.Series(name)
name

0     Rohan
1    Joseph
2     Rohit
dtype: object

In [89]:
sport = {'cricket' : 'India',
        'soccer' : 'UK',
        'Football' : 'USA'}
sport = pd.Series(sport)
sport

cricket     India
soccer         UK
Football      USA
dtype: object

## 2. Querying a Pandas Series

In [90]:
sport.iloc[2]

'USA'

In [91]:
sport.loc['Football']

'USA'

In [92]:
a = pd.Series([1,2,3])
np.sum(a) #np sum function is a faster than the in-built function

6

In [93]:
a = pd.Series([1,2,3])
#a.loc[‘City’] = ‘Delhi’
a

0    1
1    2
2    3
dtype: int64

In [94]:
# b = pd.Series([‘a’,’b’,’c’,’d’], index=[‘e’,’e’,’e’,’e’])
# b

## 3. Pandas dataframe

In [95]:
df1 = pd.DataFrame([{'Name' : 'John', 'Occupation' :  'Data Scientist', 'Age' : 25},{'Name' : 'David', 'Occupation' :  'Analyst', 'Age' : 28},{'Name' : 'Mark', 'Occupation' :  'Teacher', 'Age' : 30}],index=['1','2','3'] )
df1

Name      Occupation  Age
1   John  Data Scientist   25
2  David         Analyst   28
3   Mark         Teacher   30

In [96]:
s1 = pd.Series({'Name' : 'Rohan',
                   'Age':'25'})
s2 = pd.Series({'Name' : 'Rohit',
                'Age' : 28})
df1 = pd.DataFrame([s1,s2],index=['1','2'])
df1

Name Age
1  Rohan  25
2  Rohit  28

## 4. Read and write files

In [97]:
import pandas as pd
import numpy as np
import csv

In [104]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [111]:
ls /content/drive/MyDrive/data_science/iris.csv


/content/drive/MyDrive/data_science/iris.csv


In [112]:
path = '/content/drive/MyDrive/data_science/iris.csv'
iris = pd.read_csv(r'/content/drive/MyDrive/data_science/iris.csv')

In [113]:
iris.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [114]:
iris.to_csv('/content/drive/MyDrive/data_science/iris2.csv')

## 5. Indexing Dataframes

In [115]:
iris.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149])

In [116]:
b = iris.set_index('variety')
b.head()

sepal.length  sepal.width  petal.length  petal.width
variety                                                      
Setosa            5.1          3.5           1.4          0.2
Setosa            4.9          3.0           1.4          0.2
Setosa            4.7          3.2           1.3          0.2
Setosa            4.6          3.1           1.5          0.2
Setosa            5.0          3.6           1.4          0.2

In [117]:
c = b.reset_index()
c.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149])

In [118]:
c.head()

variety  sepal.length  sepal.width  petal.length  petal.width
0  Setosa           5.1          3.5           1.4          0.2
1  Setosa           4.9          3.0           1.4          0.2
2  Setosa           4.7          3.2           1.3          0.2
3  Setosa           4.6          3.1           1.5          0.2
4  Setosa           5.0          3.6           1.4          0.2

## 6. Merging dataframes

In [119]:
df1 = pd.read_csv(r'/content/drive/MyDrive/data_science/iris.csv')
df1.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [120]:
df2 = pd.DataFrame([{'variety' : 'setosa', 'species' : 'species 1'},
                  {'variety':'versicolor','species':'species 2'},
                   {'variety':'virginica','species':'species 3'}])
df2

variety    species
0      setosa  species 1
1  versicolor  species 2
2   virginica  species 3

In [121]:
df3 = pd.merge(df1,df2,how='inner',left_on='variety',right_on='variety')
df3.head()

Empty DataFrame
Columns: [sepal.length, sepal.width, petal.length, petal.width, variety, species]
Index: []

## 7. Aggregate function

In [122]:
df1.groupby('variety')['sepal.length'].mean()

variety
Setosa        5.006
Versicolor    5.936
Virginica     6.588
Name: sepal.length, dtype: float64

In [123]:
df1.groupby('variety')[['sepal.length','sepal.width','petal.length','petal.width']].mean()

sepal.length  sepal.width  petal.length  petal.width
variety                                                         
Setosa             5.006        3.428         1.462        0.246
Versicolor         5.936        2.770         4.260        1.326
Virginica          6.588        2.974         5.552        2.026

In [124]:
a=df1.groupby('variety').agg({'sepal.length':'mean','sepal.width':'sum'})
a

sepal.length  sepal.width
variety                              
Setosa             5.006        171.4
Versicolor         5.936        138.5
Virginica          6.588        148.7

In [125]:
a.rename(columns={'sepal.length':'Avg_sepal.length','sepal.width':'Sum_sepal.width'})

Avg_sepal.length  Sum_sepal.width
variety                                      
Setosa                 5.006            171.4
Versicolor             5.936            138.5
Virginica              6.588            148.7

## 8. Filtering Dataframes

In [126]:
a = iris[(iris['sepal.length']>7)]
a.head()

sepal.length  sepal.width  petal.length  petal.width    variety
102           7.1          3.0           5.9          2.1  Virginica
105           7.6          3.0           6.6          2.1  Virginica
107           7.3          2.9           6.3          1.8  Virginica
109           7.2          3.6           6.1          2.5  Virginica
117           7.7          3.8           6.7          2.2  Virginica

In [127]:
b = iris[(iris['sepal.length']>5) & (iris['petal.length']>6)]
b.head()

sepal.length  sepal.width  petal.length  petal.width    variety
105           7.6          3.0           6.6          2.1  Virginica
107           7.3          2.9           6.3          1.8  Virginica
109           7.2          3.6           6.1          2.5  Virginica
117           7.7          3.8           6.7          2.2  Virginica
118           7.7          2.6           6.9          2.3  Virginica

In [128]:
c = iris[iris['variety']=='Versicolor']
c.head()

sepal.length  sepal.width  petal.length  petal.width     variety
50           7.0          3.2           4.7          1.4  Versicolor
51           6.4          3.2           4.5          1.5  Versicolor
52           6.9          3.1           4.9          1.5  Versicolor
53           5.5          2.3           4.0          1.3  Versicolor
54           6.5          2.8           4.6          1.5  Versicolor

In [129]:
d = iris[iris['variety'].isin(['Virginica','Versicolor'])]
d.head()

sepal.length  sepal.width  petal.length  petal.width     variety
50           7.0          3.2           4.7          1.4  Versicolor
51           6.4          3.2           4.5          1.5  Versicolor
52           6.9          3.1           4.9          1.5  Versicolor
53           5.5          2.3           4.0          1.3  Versicolor
54           6.5          2.8           4.6          1.5  Versicolor